# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false

# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get install -y libcairo2-dev libatk1.0-dev libpango1.0-dev libgtk2.0-dev libglib2.0-dev libcurl4-openssl-dev libgdal-dev libproj-dev

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
      global:
      - R_BUILD_ARGS=" "
      - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
      - R_CHECK_TIMINGS_="0"
      - BOOTSTRAP_LATEX="1"    
      addons:
        apt:
          packages:
            - libcairo2-dev 
            - libatk1.0-dev 
            - libpango1.0-dev 
            - libgtk2.0-dev 
            - libglib2.0-dev
            - libcurl4-openssl-dev 
            - libgdal-dev 
            - libproj-dev
      r_binary_packages:
        - cairoDevice
        - RGtk2
