# Sample .travis.yml for R projects

language: r
warnings_are_errors: false
sudo: required
dist: trusty
env:
   global:
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
     - R_BUILD_ARGS=--no-manual
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
r_binary_packages:
  - cairodevice
  - rgtk2
