# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: false
sudo: required
dist: trusty
env:
   global:
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
     - R_CHECK_TIMINGS_="0"
     - BOOTSTRAP_LATEX="1"
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libcurl4-openssl-dev
      - libgtk-3-dev
r_binary_packages:
  - r-cran-cairodevice
  - r-cran-rgtk2
