# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
dist: trusty
env:
   global:
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
before_install:
  -sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
